language: node_js
node_js:
- '0.10'
before_install:
- npm install https://github.com/CooperativeHumanTissueNetwork/Vocabulary-Tooling/tarball/add-modifier-tooling
script: ./node_modules/chtn-vocabulary/node_modules/coffee-script/bin/coffee node_modules/chtn-vocabulary/index.litcoffee -f CHTN\ Vocab-Disease\ List.txt
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: VmBzdZBq5hzaFVDngDr0bH/ogZ6s0vhZpaVz0i7QmhipjC66zOfBu8BnyTgNuLw3p/Wo9O3R6iTB6phe1uuyU0F94WQfsAb4Tjuzt/7j/m7gc8+QrWaqyi8Up6XSmV2XhjRwDNhrP95CEgIUy8DFLAtlwNXn42/NDwiQ7O9xUpE=
  file:
  - '*.sql'
  - '*.json'
  file_glob: true
  on:
    repo: drobbins/Vocabulary
    tags: true
